// Build a route into site data and GPX exports.
//
//   1. Parse the trusted base GPX and attach DEM elevation (it carries none).
//   2. Load every POI category from the route's category directories.
//   3. Route each detour spur onto real paths with BRouter, and measure what it
//      actually costs in distance and ascent.
//   4. Split the loop into days at the camps and measure each day for real.
//   5. Emit site/route-data.json plus GPX for the whole route and each day.
//
// Usage: node scripts/build.mjs [routeId]

import fs from 'node:fs';
import path from 'node:path';
import { parseGpx, flattenTrack, buildGpx } from './lib/gpx.mjs';
import {
  cumulativeDistances,
  haversine,
  nearestIndex,
  totalAscent,
  totalDistance,
  simplify,
  sliceRoute,
  spliceDetour,
} from './lib/geo.mjs';
import { ElevationService } from './lib/elevation.mjs';
import { RoutingService } from './lib/brouter.mjs';
import { resolveSelection as resolveShared, dayWindow } from './lib/resolve.mjs';

const ROUTE_ID = process.argv[2] ?? 'lakeland-way';
const ROUTE_DIR = path.join('routes', ROUTE_ID);
const CATEGORY_DIRS = ['peaks', 'wild-swim-spots', 'wildcamp-spots', 'camp-spots', 'misc-poi'];

// A point this close to the line is on it — you walk past, no detour required.
const ON_ROUTE_M = 150;
const DISPLAY_TOLERANCE_M = 4;
const EXPORT_TOLERANCE_M = 3;

// --- runtime config -----------------------------------------------------------
// The OS Maps key is a credential, so it is not in the source. It comes from the
// environment (or a gitignored .env) and is written into site/config.js, which is
// also gitignored but IS included in the packaged zip. So the deployed site has the
// key and the repository never does.
//
// Without a key the page falls back to OpenStreetMap rather than showing a blank map.
const readEnvFile = () => {
  if (!fs.existsSync('.env')) return {};
  return Object.fromEntries(
    fs
      .readFileSync('.env', 'utf8')
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#'))
      .map((line) => {
        const eq = line.indexOf('=');
        return [line.slice(0, eq).trim(), line.slice(eq + 1).trim().replace(/^["']|["']$/g, '')];
      }),
  );
};

const writeRuntimeConfig = () => {
  // Normalise an empty or whitespace value to null, so "OS_MAPS_KEY=" behaves the same
  // as not setting it at all — otherwise the packager's warning would be skipped.
  const key = (process.env.OS_MAPS_KEY ?? readEnvFile().OS_MAPS_KEY ?? '').trim() || null;
  fs.mkdirSync('site', { recursive: true });
  fs.writeFileSync(
    'site/config.js',
    `${'// GENERATED by scripts/build.mjs. Gitignored — do not commit or edit.\n'}` +
      `window.APP_CONFIG = ${JSON.stringify({ osMapsKey: key })};\n`,
  );
  if (key) {
    console.log(`  config: OS Maps key present (…${key.slice(-4)}), written to site/config.js`);
  } else {
    console.log('  config: no OS_MAPS_KEY set — the page will use OpenStreetMap tiles');
  }
  return Boolean(key);
};

const cfg = JSON.parse(fs.readFileSync(path.join(ROUTE_DIR, 'route.json'), 'utf8'));
const ascentOpts = { threshold: cfg.ascent.thresholdM, smoothWindow: cfg.ascent.smoothWindow };

console.log(`\nBuilding "${cfg.name}" (${ROUTE_ID})\n`);
writeRuntimeConfig();

// --- 1. base geometry ---------------------------------------------------------
const parsed = parseGpx(fs.readFileSync(path.join(ROUTE_DIR, cfg.baseGpx), 'utf8'));
const rawTrack = flattenTrack(parsed);
const elevation = new ElevationService();
await elevation.warm(rawTrack, { label: 'base track' });
const track = elevation.attach(rawTrack);
const cum = cumulativeDistances(track);
const totalM = cum[cum.length - 1];
const totalKm = totalM / 1000;
const baseAscent = totalAscent(track, ascentOpts);

console.log(`  base: ${track.length} points, ${totalKm.toFixed(2)}km, ${baseAscent.toFixed(0)}m ascent`);

const kmAt = (index) => cum[index] / 1000;

// --- 2. POI categories --------------------------------------------------------
const categories = [];
for (const dir of CATEGORY_DIRS) {
  const full = path.join(ROUTE_DIR, dir);
  if (!fs.existsSync(full)) continue;
  const files = fs.readdirSync(full).filter((f) => f.endsWith('.json'));
  if (!files.length) continue;

  let meta = null;
  const items = [];
  for (const file of files) {
    const payload = JSON.parse(fs.readFileSync(path.join(full, file), 'utf8'));
    meta ??= payload;
    // Stamp the category on each item: the resolver needs it, because refusing to
    // double back applies to peaks only.
    for (const item of payload.items ?? []) items.push({ ...item, category: payload.category ?? dir });
  }
  if (!items.length) continue;
  categories.push({
    category: meta.category ?? dir,
    label: meta.label ?? dir,
    glyph: meta.glyph ?? '•',
    source: meta.source ?? null,
    legalNote: meta.legalNote ?? null,
    items,
  });
  console.log(`  ${dir}: ${items.length} items from ${files.length} file(s)`);
}

// --- 3. detour spurs ----------------------------------------------------------
const routing = new RoutingService();
const isCamp = (c) => c.category === 'wildcamp-spots' || c.category === 'camp-spots';

let routed = 0;
let onRoute = 0;
let unroutable = 0;

for (const cat of categories) {
  for (const item of cat.items) {
    const near = nearestIndex(track, [item.lat, item.lon]);
    item.entryKm = Number(kmAt(near.index).toFixed(3));
    item.entryIndex = near.index;
    item.offRouteM = Number(near.distance.toFixed(0));

    // Camps sit on the line by construction, and are day boundaries rather than
    // detours, so they never get a spur.
    if (isCamp(cat) || near.distance <= ON_ROUTE_M) {
      item.detour = { kind: near.distance <= ON_ROUTE_M ? 'on-route' : 'camp', addedKm: 0, addedAscentM: 0 };
      onRoute += 1;
      continue;
    }

    // A hand-authored `via` chain wins: it encodes the sensible line (which col,
    // which side of the crag). Otherwise route straight out to the point and
    // treat it as an out-and-back.
    const entryFor = (index) =>
      item.via?.length
        ? [[track[index][0], track[index][1]], ...item.via.map((v) => [v.lat ?? v[0], v.lon ?? v[1]])]
        : [[track[index][0], track[index][1]], [item.lat, item.lon]];

    let spur = await routing.route(entryFor(near.index), { label: item.title });

    // The closest point on the line is not always the right place to leave it: a
    // lake, river or crag in between can mean the walk goes a long way round.
    // When the routed spur comes out far longer than the straight-line distance
    // suggests, try leaving the route elsewhere and keep whichever is shortest.
    if (spur?.lengthM && !item.via?.length) {
      const straightOutAndBack = 2 * near.distance;
      if (spur.lengthM > 1000 + 2.2 * straightOutAndBack) {
        const alternatives = [];
        const windowM = 12000;
        for (let i = 0; i < track.length; i += 1) {
          const along = Math.abs(cum[i] - cum[near.index]);
          const wrapped = cfg.closedLoop ? Math.min(along, totalM - along) : along;
          if (wrapped < 1500 || wrapped > windowM) continue;
          alternatives.push({ index: i, d: haversine(track[i], [item.lat, item.lon]) });
        }
        alternatives.sort((a, b) => a.d - b.d);
        // Two extra probes, forced apart so they are genuinely different lines.
        const probes = [];
        for (const alt of alternatives) {
          if (probes.every((p) => Math.abs(cum[p.index] - cum[alt.index]) > 2500)) probes.push(alt);
          if (probes.length === 2) break;
        }
        for (const probe of probes) {
          const candidate = await routing.route(entryFor(probe.index), {
            label: `${item.title} (alt entry ${kmAt(probe.index).toFixed(1)}km)`,
          });
          if (candidate?.lengthM && candidate.lengthM < spur.lengthM) {
            spur = candidate;
            near.index = probe.index;
            near.distance = probe.d;
            item.entryKm = Number(kmAt(probe.index).toFixed(3));
            item.entryIndex = probe.index;
            item.offRouteM = Number(probe.d.toFixed(0));
            item.entryRelocated = true;
          }
        }
      }
    }

    if (!spur?.points?.length) {
      item.detour = { kind: 'unroutable', addedKm: null, addedAscentM: null };
      unroutable += 1;
      continue;
    }

    const outward = elevation.attach(spur.points).map((p) => p);
    const isLoop = Boolean(item.via?.length) && haversine(outward[0], outward[outward.length - 1]) > ON_ROUTE_M;
    const full = isLoop ? outward : [...outward, ...outward.slice(0, -1).reverse()];

    item.detour = {
      kind: isLoop ? 'traverse' : 'out-and-back',
      addedKm: Number((totalDistance(full) / 1000).toFixed(3)),
      addedAscentM: Number(totalAscent(full, ascentOpts).toFixed(0)),
      points: simplify(full, EXPORT_TOLERANCE_M).map((p) => [
        Number(p[0].toFixed(6)),
        Number(p[1].toFixed(6)),
        p[2] == null ? null : Number(p[2].toFixed(1)),
      ]),
    };
    routed += 1;
  }
}
elevation.flush();
routing.flush();
console.log(`  spurs: ${routed} routed, ${onRoute} on-route/camps, ${unroutable} unroutable`);

// --- 3b. traverses -----------------------------------------------------------
// An out-and-back is the safe way to reach a summit but rarely the natural one.
// Where the route passes near the same fell twice, it is better to leave the line
// at one point, walk over the top, and rejoin further on: the cost is then the
// traverse minus the base route it replaces, which is far less than doubling back.
//
// Both geometries are kept. The out-and-back stays as the fallback for when two
// selected traverses would replace overlapping stretches of the same base route.
const MAX_BYPASS_KM = 10;
const MIN_BYPASS_KM = 0.4;

// Each local minimum of distance-to-target along the route is a distinct place the
// route comes close, so a natural candidate for leaving or rejoining it.
const approachPoints = (target, { minSeparationM = 1200, limit = 5 } = {}) => {
  const d = track.map((p) => haversine(p, target));
  const minima = [];
  for (let i = 1; i < d.length - 1; i += 1) {
    if (d[i] <= d[i - 1] && d[i] <= d[i + 1]) minima.push({ index: i, dist: d[i] });
  }
  minima.sort((a, b) => a.dist - b.dist);
  const kept = [];
  for (const m of minima) {
    if (kept.every((k) => Math.abs(cum[k.index] - cum[m.index]) > minSeparationM)) kept.push(m);
    if (kept.length >= limit) break;
  }
  return kept.sort((a, b) => cum[a.index] - cum[b.index]);
};

const campKmList = (categories.find((c) => c.category === 'wildcamp-spots')?.items ?? []).map(
  (c) => c.entryKm,
);
// A traverse may not swallow a camp, or you would walk past the night's stop.
const spansCamp = (aKm, bKm) => campKmList.some((k) => k > aKm + 0.01 && k < bKm - 0.01);

const baseAscentBetween = (from, to) => totalAscent(track.slice(from, to + 1), ascentOpts);

const traverseTargets = categories
  .filter((c) => !isCamp(c))
  .flatMap((cat) => cat.items.filter((i) => i.starred && i.detour?.points?.length));

let traversesFound = 0;
for (const item of traverseTargets) {
  const approaches = approachPoints([item.lat, item.lon]);
  let best = null;
  for (let x = 0; x < approaches.length; x += 1) {
    for (let y = x + 1; y < approaches.length; y += 1) {
      const A = approaches[x];
      const B = approaches[y];
      const replacedKm = (cum[B.index] - cum[A.index]) / 1000;
      if (replacedKm < MIN_BYPASS_KM || replacedKm > MAX_BYPASS_KM) continue;
      const aKm = cum[A.index] / 1000;
      const bKm = cum[B.index] / 1000;
      if (spansCamp(aKm, bKm)) continue;

      const spur = await routing.route(
        [
          [track[A.index][0], track[A.index][1]],
          [item.lat, item.lon],
          [track[B.index][0], track[B.index][1]],
        ],
        { label: `${item.title} traverse ${aKm.toFixed(1)}->${bKm.toFixed(1)}` },
      );
      if (!spur?.points?.length) continue;

      const pts = elevation.attach(spur.points);
      const traverseKm = totalDistance(pts) / 1000;
      const netKm = traverseKm - replacedKm;
      if (netKm <= 0.05) continue; // implausible: treat as a bad match
      const netAscent = totalAscent(pts, ascentOpts) - baseAscentBetween(A.index, B.index);
      if (!best || netKm < best.addedKm) {
        best = {
          kind: 'traverse',
          addedKm: Number(netKm.toFixed(3)),
          addedAscentM: Number(Math.max(0, netAscent).toFixed(0)),
          replacedKm: Number(replacedKm.toFixed(3)),
          traverseKm: Number(traverseKm.toFixed(3)),
          fromKm: Number(aKm.toFixed(3)),
          toKm: Number(bKm.toFixed(3)),
          points: simplify(pts, EXPORT_TOLERANCE_M).map((p) => [
            Number(p[0].toFixed(6)),
            Number(p[1].toFixed(6)),
            p[2] == null ? null : Number(p[2].toFixed(1)),
          ]),
        };
      }
    }
  }
  // Only worth offering if it genuinely beats doubling back.
  if (best && best.addedKm < item.detour.addedKm - 0.1) {
    item.traverse = best;
    traversesFound += 1;
  }
}
elevation.flush();
routing.flush();

// A traverse walks past things. Any other point close to its line is collected on
// the way rather than orphaned by it — Emerald Pools sits in Lingmell Beck, which
// the Scafell Pike traverse follows, so it costs nothing extra and needs no spur.
// Recording that both prices the day correctly and stops a good traverse being
// withdrawn to protect a point it already visits.
const COLLECT_M = 300;
const allDetourItems = categories.filter((c) => !isCamp(c)).flatMap((c) => c.items);
const poisNear = (points, excludeIds) => {
  const found = [];
  for (const other of allDetourItems) {
    if (excludeIds.includes(other.id)) continue;
    let best = Infinity;
    for (const p of points) {
      const d = haversine(p, [other.lat, other.lon]);
      if (d < best) best = d;
      if (best <= COLLECT_M) break;
    }
    if (best <= COLLECT_M) found.push(other.id);
  }
  return found;
};
for (const item of traverseTargets) {
  if (!item.traverse) continue;
  item.traverse.collects = poisNear(item.traverse.points, [item.id]);
}

const savings = traverseTargets
  .filter((i) => i.traverse)
  .reduce((s, i) => s + (i.detour.addedKm - i.traverse.addedKm), 0);
console.log(
  `  traverses: ${traversesFound} of ${traverseTargets.length} starred points improved, saving ${savings.toFixed(1)}km in total`,
);

// The cost that matters for planning is whichever option is cheaper.
const effective = (item) => item.traverse ?? item.detour;

// --- 4. days ------------------------------------------------------------------
const camps = (categories.find((c) => c.category === 'wildcamp-spots')?.items ?? [])
  .slice()
  .sort((a, b) => a.entryKm - b.entryKm);
if (camps.length !== cfg.days - 1) {
  console.error(
    `  warning: ${camps.length} camps for ${cfg.days} days (expected ${cfg.days - 1}); day splits may be wrong`,
  );
}

const boundaryIdx = [0, ...camps.map((c) => c.entryIndex), track.length - 1];
const startDate = new Date(`${cfg.startDate}T00:00:00Z`);
const dateFor = (dayNumber) => {
  const d = new Date(startDate);
  d.setUTCDate(d.getUTCDate() + dayNumber - 1);
  return d.toISOString().slice(0, 10);
};

const buildDays = (reverse) => {
  const days = [];
  for (let d = 0; d < cfg.days; d += 1) {
    // Anticlockwise walks the same loop the other way, so day 1 is the final
    // clockwise leg reversed, and so on back through the list.
    const seg = reverse
      ? sliceRoute(track, boundaryIdx[cfg.days - d - 1], boundaryIdx[cfg.days - d]).slice().reverse()
      : sliceRoute(track, boundaryIdx[d], boundaryIdx[d + 1]);
    const startKm = reverse ? totalKm - kmAt(boundaryIdx[cfg.days - d]) : kmAt(boundaryIdx[d]);
    const endKm = reverse ? totalKm - kmAt(boundaryIdx[cfg.days - d - 1]) : kmAt(boundaryIdx[d + 1]);
    const campSourceIndex = reverse ? cfg.days - d - 2 : d;
    days.push({
      day: d + 1,
      date: dateFor(d + 1),
      startKm: Number(startKm.toFixed(2)),
      endKm: Number(endKm.toFixed(2)),
      baseKm: Number((totalDistance(seg) / 1000).toFixed(2)),
      baseAscentM: Number(totalAscent(seg, ascentOpts).toFixed(0)),
      campId: campSourceIndex >= 0 && campSourceIndex < camps.length ? camps[campSourceIndex].id : null,
      points: simplify(seg, DISPLAY_TOLERANCE_M).map((p) => [
        Number(p[0].toFixed(6)),
        Number(p[1].toFixed(6)),
        p[2] == null ? null : Number(p[2].toFixed(1)),
      ]),
    });
  }
  return days;
};

const directions = {};
for (const [key, meta] of Object.entries(cfg.directions)) {
  const days = buildDays(meta.reverse);
  directions[key] = { label: meta.label, reverse: meta.reverse, days };
  console.log(
    `  ${key}: days ${days.map((d) => d.baseKm.toFixed(1)).join(', ')} (base only)`,
  );
}

// Assign each POI to a day in each direction, by where it meets the line.
for (const cat of categories) {
  for (const item of cat.items) {
    item.dayByDirection = {};
    for (const [key, dir] of Object.entries(directions)) {
      const km = dir.reverse ? totalKm - item.entryKm : item.entryKm;
      const found = dir.days.find((d) => km >= d.startKm - 1e-6 && km <= d.endKm + 1e-6);
      item.dayByDirection[key] = found ? found.day : null;
    }
  }
}

// --- 5. outputs ---------------------------------------------------------------
const exportDir = path.join(ROUTE_DIR, 'gpx-exports');
fs.mkdirSync(exportDir, { recursive: true });
for (const name of fs.readdirSync(exportDir).filter((n) => n.endsWith('.gpx'))) {
  fs.unlinkSync(path.join(exportDir, name));
}

const written = [];
const writeGpx = (file, payload) => {
  fs.writeFileSync(path.join(exportDir, file), buildGpx(payload));
  written.push(file);
};

const poiWaypoint = (item, cat) => ({
  lat: item.lat,
  lon: item.lon,
  ele: item.heightM ?? item.elevationM ?? null,
  name: item.heightM ? `${item.title} ${item.heightM}m` : item.title,
  desc:
    [
      item.description,
      item.detour?.addedKm ? `Detour: +${item.detour.addedKm.toFixed(1)}km, +${item.detour.addedAscentM}m ascent.` : null,
      item.offRouteM <= ON_ROUTE_M ? 'On the route.' : null,
    ]
      .filter(Boolean)
      .join(' ') || null,
  type: cat.category,
});

const detourCats = categories.filter((c) => !isCamp(c));

// --- recommended itinerary ----------------------------------------------------
// Starring marks a detour as worth doing; it says nothing about whether it fits.
// Taking every starred detour puts five days over the ceiling and day 2 at 48km,
// so the recommended set is chosen against the real budget: no day over
// planning.maxDayKm, and the whole trip averaging no more than targetAverageKm.
//
// Preference goes to the best detours per kilometre walked, so a short spur onto
// a classic summit beats a long haul to a minor one.
const recommendedFor = (dirKey) => {
  const dir = directions[dirKey];
  const globalBudgetKm = Math.max(0, cfg.planning.targetAverageKm * cfg.days - totalKm);

  const value = (item, cat) => {
    let v = item.starred ? 10 : item.description ? 3 : 1;
    if (cat.category === 'peaks' && item.heightM) v += item.heightM / 250;
    if (item.offRouteM <= ON_ROUTE_M) v += 4; // free — already on the line
    return v;
  };

  const chosen = new Set();
  const spendByDay = new Map();
  const usedRangesByDay = new Map();
  let spent = 0;

  // Cost of adding this point given what is already selected on its day. Two
  // traverses cannot replace the same stretch of base route, so the second one
  // has to double back — and it must be budgeted at that higher price, or the
  // plan overruns the moment it is actually walked. Chains are applied later and
  // only ever reduce this, so planning with the conservative figure is safe.
  const marginalKm = (item, day) => {
    const used = usedRangesByDay.get(day) ?? [];
    if (item.traverse) {
      const clash = used.some(
        ([a, b]) => item.traverse.fromKm < b - 0.01 && item.traverse.toKm > a + 0.01,
      );
      if (!clash) return { km: item.traverse.addedKm, range: [item.traverse.fromKm, item.traverse.toKm] };
    }
    return { km: item.detour.addedKm ?? 0, range: null };
  };

  const pool = detourCats
    .flatMap((cat) => cat.items.map((item) => ({ item, cat })))
    .filter((e) => e.item.detour?.kind === 'on-route' || e.item.detour?.points?.length)
    .map((entry) => ({
      item: entry.item,
      cat: entry.cat,
      day: entry.item.dayByDirection[dirKey],
      // Ranking uses the optimistic cost so good traverses are considered early;
      // the actual charge is recomputed conflict-aware when it is taken.
      km: effective(entry.item).addedKm ?? 0,
      value: value(entry.item, entry.cat),
    }))
    .filter((e) => e.day != null)
    .sort((a, b) => b.value / Math.max(0.25, b.km) - a.value / Math.max(0.25, a.km));

  // Anything genuinely on the line costs nothing, so it is always included.
  for (const e of pool.filter((p) => p.km === 0)) chosen.add(e.item.id);

  const dayTotal = (dayNumber, extra = 0) => {
    const day = dir.days.find((d) => d.day === dayNumber);
    if (!day) return 0;
    return day.baseKm + (spendByDay.get(dayNumber) ?? 0) + extra;
  };

  // Back-to-back long days are what actually breaks a trip, so cap how many may
  // run consecutively even when each one is individually inside the ceiling.
  const createsTooLongARun = (dayNumber, extra) => {
    if (dayTotal(dayNumber, extra) < cfg.planning.longDayKm) return false;
    let run = 1;
    for (let d = dayNumber - 1; d >= 1; d -= 1) {
      if (dayTotal(d) < cfg.planning.longDayKm) break;
      run += 1;
    }
    for (let d = dayNumber + 1; d <= cfg.days; d += 1) {
      if (dayTotal(d) < cfg.planning.longDayKm) break;
      run += 1;
    }
    return run > cfg.planning.maxConsecutiveLongDays;
  };

  for (const e of pool.filter((p) => p.km > 0)) {
    const day = dir.days.find((d) => d.day === e.day);
    if (!day) continue;
    const { km: cost, range } = marginalKm(e.item, e.day);
    const dayUsed = spendByDay.get(e.day) ?? 0;
    if (day.baseKm + dayUsed + cost > cfg.planning.maxDayKm) continue;
    if (spent + cost > globalBudgetKm) continue;
    if (createsTooLongARun(e.day, cost)) continue;
    chosen.add(e.item.id);
    spendByDay.set(e.day, dayUsed + cost);
    spent += cost;
    if (range) {
      if (!usedRangesByDay.has(e.day)) usedRangesByDay.set(e.day, []);
      usedRangesByDay.get(e.day).push(range);
    }
  }
  return { ids: chosen, spentKm: spent, budgetKm: globalBudgetKm };
};

const recommended = {};
for (const key of Object.keys(directions)) {
  recommended[key] = recommendedFor(key);
  const r = recommended[key];
  console.log(
    `  ${key}: recommended ${r.ids.size} detours, +${r.spentKm.toFixed(1)}km of ${r.budgetKm.toFixed(1)}km budget`,
  );
}

const isRecommended = (item, dirKey) => recommended[dirKey].ids.has(item.id);

// --- chained traverses --------------------------------------------------------
// Where several recommended summits sit on the same stretch, their traverses
// overlap and splicing them one by one would corrupt the line and double-count
// the shared climbing. The natural walk is a single line over all of them, so
// each overlapping group is re-routed as one chain through every summit in route
// order. Computed only for the recommended set, which keeps it to a handful of
// routing calls.
const chains = [];
{
  const byId = new Map();
  for (const cat of categories.filter((c) => !isCamp(c))) {
    for (const item of cat.items) byId.set(item.id, item);
  }
  const seenGroups = new Set();
  for (const key of Object.keys(directions)) {
    const withTraverse = [...recommended[key].ids]
      .map((id) => byId.get(id))
      .filter((i) => i?.traverse)
      .sort((a, b) => a.traverse.fromKm - b.traverse.fromKm);

    // Group by overlapping [fromKm, toKm] ranges.
    const groups = [];
    for (const item of withTraverse) {
      const last = groups[groups.length - 1];
      if (last && item.traverse.fromKm < last.toKm - 0.01) {
        last.items.push(item);
        last.toKm = Math.max(last.toKm, item.traverse.toKm);
      } else {
        groups.push({ items: [item], fromKm: item.traverse.fromKm, toKm: item.traverse.toKm });
      }
    }

    for (const group of groups) {
      if (group.items.length < 2) continue;
      const ids = group.items.map((i) => i.id).sort();
      const groupKey = ids.join('|');
      if (seenGroups.has(groupKey)) continue;
      seenGroups.add(groupKey);

      const replacedKm = group.toKm - group.fromKm;
      if (replacedKm > MAX_BYPASS_KM) continue;
      if (spansCamp(group.fromKm, group.toKm)) continue;

      const entry = nearestIndex(track, [
        track[Math.round((group.fromKm / totalKm) * (track.length - 1))][0],
        track[Math.round((group.fromKm / totalKm) * (track.length - 1))][1],
      ]);
      // Resolve exact entry/exit indices from the km positions.
      const idxAtKm = (targetKm) => {
        let best = 0;
        let bestD = Infinity;
        for (let i = 0; i < cum.length; i += 1) {
          const d = Math.abs(cum[i] / 1000 - targetKm);
          if (d < bestD) {
            bestD = d;
            best = i;
          }
        }
        return best;
      };
      const aIdx = idxAtKm(group.fromKm);
      const bIdx = idxAtKm(group.toKm);
      void entry;

      // Visit the summits in the order the walk reaches them.
      const ordered = group.items.slice().sort((a, b) => a.entryKm - b.entryKm);
      const chained = await routing.route(
        [
          [track[aIdx][0], track[aIdx][1]],
          ...ordered.map((i) => [i.lat, i.lon]),
          [track[bIdx][0], track[bIdx][1]],
        ],
        { label: `chain: ${ordered.map((i) => i.title).join(' + ')}` },
      );
      if (!chained?.points?.length) continue;

      const pts = elevation.attach(chained.points);
      const chainKm = totalDistance(pts) / 1000;
      const netKm = chainKm - replacedKm;
      const netAscent = totalAscent(pts, ascentOpts) - baseAscentBetween(aIdx, bIdx);
      const separateKm = ordered.reduce((s, i) => s + i.traverse.addedKm, 0);
      // Only adopt the chain if it beats doing them as separate traverses.
      if (netKm >= separateKm) continue;

      const chainPoints = simplify(pts, EXPORT_TOLERANCE_M);
      chains.push({
        collects: poisNear(chainPoints, ordered.map((i) => i.id)),
        id: `chain-${ids.map((i) => i.replace(/^(peak|swim)-/, '')).join('-')}`.slice(0, 90),
        title: ordered.map((i) => i.title).join(' + '),
        memberIds: ordered.map((i) => i.id),
        addedKm: Number(netKm.toFixed(3)),
        addedAscentM: Number(Math.max(0, netAscent).toFixed(0)),
        replacedKm: Number(replacedKm.toFixed(3)),
        fromKm: Number(group.fromKm.toFixed(3)),
        toKm: Number(group.toKm.toFixed(3)),
        separateKm: Number(separateKm.toFixed(3)),
        points: simplify(pts, EXPORT_TOLERANCE_M).map((p) => [
          Number(p[0].toFixed(6)),
          Number(p[1].toFixed(6)),
          p[2] == null ? null : Number(p[2].toFixed(1)),
        ]),
      });
    }
  }
  elevation.flush();
  routing.flush();
  if (chains.length) {
    for (const c of chains) {
      console.log(
        `  chain: ${c.title} -> +${c.addedKm}km (vs ${c.separateKm}km separate), replaces ${c.replacedKm}km`,
      );
    }
  } else {
    console.log('  chains: none improved on separate traverses');
  }
}

const chainForItem = (item) => chains.find((c) => c.memberIds.includes(item.id));

// Anything a traverse or chain walks past can be reached without doubling back.
const collectableIds = new Set([
  ...allDetourItems.flatMap((i) => i.traverse?.collects ?? []),
  ...chains.flatMap((c) => c.collects ?? []),
]);

// --- repair the recommendation against the real resolution ---------------------
// The selector is a heuristic run before chains exist, and it claims traverse
// ranges in value order. The browser resolves chains first and then traverses in
// data order, so the two can disagree about which detour has to fall back to
// doubling back — and a fallback costs more. Rather than trust the estimate, the
// plan is now re-resolved exactly as the browser will, and trimmed until it
// genuinely fits.
const itemsById = new Map();
for (const cat of categories.filter((c) => !isCamp(c))) {
  for (const item of cat.items) itemsById.set(item.id, item);
}
// Every consumer goes through the one shared resolver in lib/resolve.mjs.
function resolveSelection(dayNumber, dirKey, ids, opts = {}) {
  const dir = directions[dirKey];
  const day = dir.days.find((d) => d.day === dayNumber);
  return resolveShared({
    items: [...itemsById.values()],
    chains,
    dayNumber,
    direction: dirKey,
    selectedIds: ids,
    window: day ? dayWindow(day, dir.reverse, totalKm) : null,
    ...opts,
  });
}

// Trim an over-full plan and then refill any budget left, judged against the real
// resolver. Used for both plan flavours: the normal one, and the "nothing doubles
// back" one where every summit must be walked over or passed.
function fitPlan(dirKey, ids, { excludeOutAndBack = false, seedFrom = null } = {}) {
  const dir = directions[dirKey];
  const resolveKm = (dayNumber) =>
    resolveSelection(dayNumber, dirKey, ids, { excludeOutAndBack }).addedKm;

  const rank = (item) => {
    const km = Math.max(0.25, effective(item).addedKm ?? 0);
    const v = (item.starred ? 10 : item.description ? 3 : 1) + (item.heightM ? item.heightM / 250 : 0);
    return v / km; // lowest first = cheapest to give up
  };

  const P = cfg.planning;
  const endCap = P.endDayMaxKm ?? P.maxDayKm;
  // Day 1 and the final day are travel days and carry a tighter ceiling.
  const capFor = (dayNumber) => (dayNumber === 1 || dayNumber === cfg.days ? endCap : P.maxDayKm);
  const isMiddle = (dayNumber) => dayNumber !== 1 && dayNumber !== cfg.days;
  const countEasyMiddle = (t) =>
    t.filter((x, i) => isMiddle(dir.days[i].day) && x <= P.easyDayKm).length;

  const totalsNow = () => dir.days.map((d) => d.baseKm + resolveKm(d.day));
  const fits = () => {
    const t = totalsNow();
    if (t.some((x, i) => x > capFor(dir.days[i].day) + 1e-6)) return false;
    if (t.reduce((s, x) => s + x, 0) / t.length > P.targetAverageKm + 1e-6) return false;
    let run = 0;
    for (const x of t) {
      run = x >= P.longDayKm ? run + 1 : 0;
      if (run > P.maxConsecutiveLongDays) return false;
    }
    // Keep genuine short days mid-trip. Not days off, just easier ones. Without
    // this the top-up pass fills every day to the ceiling and the itinerary becomes
    // twelve hard days in a row.
    if (P.minEasyMiddleDays && countEasyMiddle(t) < P.minEasyMiddleDays) return false;
    return true;
  };

  let trimmed = 0;
  // Days with nothing left worth removing. Without this the loop gave up entirely on
  // hitting one, instead of moving on to a day it could still fix.
  const exhausted = new Set();
  for (let guard = 0; guard < 400; guard += 1) {
    const totals = dir.days.map((d) => ({ day: d, total: d.baseKm + resolveKm(d.day) }));
    const avg = totals.reduce((s, t) => s + t.total, 0) / dir.days.length;
    // Three reasons to trim, in priority order: a day over its ceiling, the trip
    // average over target, or too few short days mid-trip. For the last of these the
    // cheapest fix is the middle day already closest to the short-day threshold.
    const tooFewEasy =
      P.minEasyMiddleDays && countEasyMiddle(totals.map((t) => t.total)) < P.minEasyMiddleDays;
    const open = totals.filter((t) => !exhausted.has(t.day.day));
    const offender =
      open.find((t) => t.total > capFor(t.day.day) + 1e-6) ??
      (avg > P.targetAverageKm + 1e-6
        ? open.slice().sort((a, b) => b.total - a.total)[0]
        : tooFewEasy
          ? open
              .filter((t) => isMiddle(t.day.day) && t.total > P.easyDayKm)
              // Cheapest fix first: the day already nearest the threshold. Only
              // consider days whose base is low enough to ever get there.
              .filter((t) => t.day.baseKm <= P.easyDayKm)
              .sort((a, b) => a.total - b.total)[0]
          : null);
    if (!offender) break;

    const onDay = [...ids]
      .map((id) => itemsById.get(id))
      .filter((i) => i && i.dayByDirection[dirKey] === offender.day.day && (effective(i).addedKm ?? 0) > 0)
      .sort((a, b) => rank(a) - rank(b));
    if (!onDay.length) {
      exhausted.add(offender.day.day);
      continue;
    }

    // Dropping one member of a chain would break the chain and make the rest
    // dearer, so a chain is always given up whole.
    const victim = onDay[0];
    const chain = chainForItem(victim);
    if (chain) for (const id of chain.memberIds) ids.delete(id);
    else ids.delete(victim.id);
    trimmed += 1;
  }

  let added = 0;
  const pool = (seedFrom ?? [...itemsById.values()])
    .filter((i) => !ids.has(i.id) && i.dayByDirection[dirKey] != null)
    .filter((i) => i.detour?.kind === 'on-route' || i.detour?.points?.length)
    .sort((a, b) => rank(b) - rank(a));
  for (const item of pool) {
    ids.add(item.id);
    if (fits()) added += 1;
    else ids.delete(item.id);
  }

  const totals = totalsNow();
  return {
    ids,
    trimmed,
    added,
    spentKm: totals.reduce((s, t) => s + t, 0) - totalKm,
    maxDayKm: Math.max(...totals),
    avgKm: totals.reduce((s, t) => s + t, 0) / totals.length,
    endDays: [totals[0], totals[totals.length - 1]],
    easyMiddleDays: countEasyMiddle(totals),
  };
}

for (const key of Object.keys(directions)) {
  const r = fitPlan(key, recommended[key].ids);
  recommended[key].spentKm = r.spentKm;
  console.log(
    `  ${key}: resolved plan ${recommended[key].ids.size} detours, +${r.spentKm.toFixed(1)}km, ` +
      `max day ${r.maxDayKm.toFixed(1)}km, avg ${r.avgKm.toFixed(1)}km, travel ${r.endDays.map((x) => x.toFixed(1)).join('/')}km, ${r.easyMiddleDays} short` +
      (r.trimmed ? ` (trimmed ${r.trimmed})` : '') +
      (r.added ? ` (topped up ${r.added})` : ''),
  );
}

// --- second plan flavour: nothing doubles back --------------------------------
// Every point must be walked over, chained, passed on the way, or already on the
// line. With no out-and-backs to orphan, more traverses become usable — Scafell
// Pike and Blea Water among them.
// Whether a point survives the "no there-and-back" plan. Only peaks are ever
// dropped by it — a swim or a campsite may be walked out to and back from.
const EXCLUDE_CATEGORIES = ['peaks'];
const canAvoidBacktrack = (item) =>
  !EXCLUDE_CATEGORIES.includes(item.category) ||
  item.detour?.kind === 'on-route' ||
  Boolean(item.traverse) ||
  Boolean(chainForItem(item)) ||
  collectableIds.has(item.id);

const recommendedNoBacktrack = {};
for (const key of Object.keys(directions)) {
  const seed = new Set(
    [...itemsById.values()].filter((i) => canAvoidBacktrack(i) && i.dayByDirection[key] != null).map((i) => i.id),
  );
  const r = fitPlan(key, seed, {
    excludeOutAndBack: true,
    seedFrom: [...itemsById.values()].filter(canAvoidBacktrack),
  });
  recommendedNoBacktrack[key] = { ids: [...seed], spentKm: Number(r.spentKm.toFixed(2)) };
  console.log(
    `  ${key}: over-the-top-only plan ${seed.size} points, +${r.spentKm.toFixed(1)}km, ` +
      `max day ${r.maxDayKm.toFixed(1)}km, avg ${r.avgKm.toFixed(1)}km, travel ${r.endDays.map((x) => x.toFixed(1)).join('/')}km, ${r.easyMiddleDays} short`,
  );
}

const recommendedItems = (cat, dirKey) =>
  cat.items.filter((i) => isRecommended(i, dirKey) && i.detour?.points?.length);

// Whole route, base line only.
writeGpx(`${ROUTE_ID}-full-base.gpx`, {
  name: `${cfg.name} — full route`,
  desc: `${totalKm.toFixed(1)}km, ${baseAscent.toFixed(0)}m ascent. Base route as drawn, no detours.`,
  tracks: [{ name: cfg.name, points: simplify(track, EXPORT_TOLERANCE_M) }],
  waypoints: camps.map((c) => ({ lat: c.lat, lon: c.lon, name: c.title, desc: c.description, type: 'camp' })),
});

// Whole route with the recommended (budgeted) detours spliced in, per direction.
for (const [key, dir] of Object.entries(directions)) {
  let spliced = track.slice();
  let addedKm = 0;
  let addedAscent = 0;
  // Resolve per day so clashing traverses are handled the same way the browser
  // and verify.mjs handle them.
  for (const day of dir.days) {
    const r = resolveSelection(day.day, key, recommended[key].ids);
    for (const part of r.parts) {
      if (part.points?.length) spliced = spliceDetour(spliced, part.points, { closed: cfg.closedLoop });
    }
    addedKm += r.addedKm;
    addedAscent += r.addedAscentM;
  }
  writeGpx(`${ROUTE_ID}-${key}-full-recommended.gpx`, {
    name: `${cfg.name} — ${dir.label}, full route with recommended detours`,
    desc:
      `Base ${totalKm.toFixed(1)}km plus ${addedKm.toFixed(1)}km of peak and swim detours ` +
      `(+${addedAscent.toFixed(0)}m ascent), chosen so no day exceeds ${cfg.planning.maxDayKm}km ` +
      `and the trip averages under ${cfg.planning.targetAverageKm}km.`,
    tracks: [{ name: `${cfg.name} (with detours)`, points: simplify(spliced, EXPORT_TOLERANCE_M) }],
    waypoints: detourCats.flatMap((cat) =>
      recommendedItems(cat, key).map((i) => poiWaypoint(i, cat)),
    ),
  });
}

// Whole route, over-the-top-only plan.
for (const [key, dir] of Object.entries(directions)) {
  const ids = new Set(recommendedNoBacktrack[key].ids);
  let spliced = track.slice();
  let addedKm = 0;
  let addedAscent = 0;
  const waypoints = [];
  for (const day of dir.days) {
    const r = resolveSelection(day.day, key, ids, { excludeOutAndBack: true });
    for (const part of r.parts) {
      if (part.points?.length) spliced = spliceDetour(spliced, part.points, { closed: cfg.closedLoop });
    }
    addedKm += r.addedKm;
    addedAscent += r.addedAscentM;
    for (const item of r.picked) {
      if (r.modes.get(item.id) === 'excluded') continue;
      const cat = detourCats.find((c) => c.items.includes(item));
      if (cat) waypoints.push(poiWaypoint(item, cat));
    }
  }
  writeGpx(`${ROUTE_ID}-${key}-full-over-the-top.gpx`, {
    name: `${cfg.name} — ${dir.label}, over the top only`,
    desc:
      `Base ${totalKm.toFixed(1)}km plus ${addedKm.toFixed(1)}km (+${addedAscent.toFixed(0)}m ascent). ` +
      'Every summit and swim on this line is walked over, chained, or passed on the way — nothing doubles back.',
    tracks: [{ name: `${cfg.name} (over the top)`, points: simplify(spliced, EXPORT_TOLERANCE_M) }],
    waypoints,
  });
}

// Per-category files.
for (const cat of detourCats) {
  const withSpurs = cat.items.filter((i) => i.detour?.points?.length);
  writeGpx(`${ROUTE_ID}-${cat.category}.gpx`, {
    name: `${cfg.name} — ${cat.label}`,
    desc: `${cat.items.length} ${cat.label.toLowerCase()} near the route. ${cat.source ?? ''}`.trim(),
    waypoints: cat.items.map((i) => poiWaypoint(i, cat)),
    tracks: withSpurs.map((i) => ({
      name: `${i.title} detour`,
      desc: `+${i.detour.addedKm.toFixed(1)}km, +${i.detour.addedAscentM}m ascent (${i.detour.kind}).`,
      points: i.detour.points,
    })),
  });
}

// Per-day files, in both directions, with that day's starred detours spliced in.
for (const [key, dir] of Object.entries(directions)) {
  for (const day of dir.days) {
    const dayPois = detourCats.flatMap((cat) =>
      cat.items
        .filter(
          (i) => isRecommended(i, key) && i.detour?.points?.length && i.dayByDirection[key] === day.day,
        )
        .map((i) => ({ item: i, cat })),
    );
    const resolved = resolveSelection(day.day, key, recommended[key].ids);
    let pts = day.points.slice();
    for (const part of resolved.parts) {
      if (part.points?.length) pts = spliceDetour(pts, part.points);
    }
    const extraKm = resolved.addedKm;
    const extraAscent = resolved.addedAscentM;
    const label = String(day.day).padStart(2, '0');
    writeGpx(`${ROUTE_ID}-${key}-day-${label}.gpx`, {
      name: `${cfg.name} — ${dir.label} day ${day.day} (${day.date})`,
      desc:
        `Base ${day.baseKm.toFixed(1)}km, +${day.baseAscentM}m` +
        (dayPois.length
          ? `; with ${dayPois.length} detour(s): +${extraKm.toFixed(1)}km, +${extraAscent.toFixed(0)}m ascent. Total ${(day.baseKm + extraKm).toFixed(1)}km.`
          : '; no detours on this day.'),
      tracks: [{ name: `Day ${day.day}`, points: pts }],
      waypoints: [
        ...dayPois.map(({ item, cat }) => poiWaypoint(item, cat)),
        ...camps
          .filter((c) => c.id === day.campId)
          .map((c) => ({ lat: c.lat, lon: c.lon, name: `${c.title} — camp`, desc: c.description, type: 'camp' })),
      ],
    });
  }
}

// Also place them inside the publish directory. Netlify publishes site/, so a link
// to ../routes/... resolves above the site root and 404s — it only worked locally
// because the dev server was rooted at the repo. routes/<id>/gpx-exports stays the
// canonical per-route location; this is the served copy.
const siteGpxDir = path.join('site', 'gpx', ROUTE_ID);
fs.mkdirSync(siteGpxDir, { recursive: true });
for (const name of fs.readdirSync(siteGpxDir).filter((n) => n.endsWith('.gpx'))) {
  fs.unlinkSync(path.join(siteGpxDir, name));
}
for (const f of written) {
  fs.copyFileSync(path.join(exportDir, f), path.join(siteGpxDir, f));
}
console.log(`  gpx: ${written.length} files in ${exportDir} (copied to ${siteGpxDir})`);

// --- site data ----------------------------------------------------------------
const siteData = {
  generatedFrom: {
    route: ROUTE_ID,
    baseGpx: cfg.baseGpx,
    elevation: cfg.attribution.elevation,
    detourRouting: cfg.attribution.detourRouting,
  },
  route: {
    id: ROUTE_ID,
    name: cfg.name,
    days: cfg.days,
    startDate: cfg.startDate,
    closedLoop: cfg.closedLoop,
    totalKm: Number(totalKm.toFixed(2)),
    ascentM: Number(baseAscent.toFixed(0)),
    planning: cfg.planning,
    note: cfg.measured.note,
  },
  directions,
  categories: categories.map((cat) => ({
    category: cat.category,
    label: cat.label,
    glyph: cat.glyph,
    source: cat.source,
    legalNote: cat.legalNote,
    items: cat.items.map((i) => ({
      id: i.id,
      title: i.title,
      lat: i.lat,
      lon: i.lon,
      description: i.description,
      labels: i.labels ?? [],
      starred: Boolean(i.starred),
      heightM: i.heightM ?? null,
      elevationM: i.elevationM ?? null,
      night: i.night ?? null,
      offRouteM: i.offRouteM,
      entryKm: i.entryKm,
      dayByDirection: i.dayByDirection,
      needsEntryPoint: i.needsEntryPoint ?? false,
      entryRelocated: Boolean(i.entryRelocated),
      recommendedIn: Object.keys(directions).filter((k) => isRecommended(i, k)),
      detour: i.detour,
      traverse: i.traverse ?? null,
      category: i.category,
      chainId: chainForItem(i)?.id ?? null,
      noBacktrack: canAvoidBacktrack(i),
    })),
  })),
  chains,
  recommended: Object.fromEntries(
    Object.entries(recommended).map(([k, r]) => [
      k,
      { ids: [...r.ids], spentKm: Number(r.spentKm.toFixed(2)), budgetKm: Number(r.budgetKm.toFixed(2)) },
    ]),
  ),
  recommendedNoBacktrack,
  exports: [...written].sort(),
};

fs.mkdirSync('site', { recursive: true });
fs.writeFileSync('site/route-data.json', `${JSON.stringify(siteData)}\n`);

// Generate the browser's copy of the resolver from the same file the build uses,
// so the page can never disagree with the exports about what a day costs.
const resolverSrc = fs.readFileSync('scripts/lib/resolve.mjs', 'utf8');
fs.writeFileSync(
  'site/resolve.js',
  `${'// GENERATED by scripts/build.mjs from scripts/lib/resolve.mjs — do not edit.\n'}${resolverSrc
    .replace(/^export function/gm, 'function')
    .trimEnd()}\nwindow.resolveSelection = resolveSelection;\nwindow.dayWindow = dayWindow;\n`,
);
const sizeMb = fs.statSync('site/route-data.json').size / 1e6;
console.log(`  site/route-data.json: ${sizeMb.toFixed(2)} MB\n`);

const allItems = detourCats.flatMap((c) => c.items);
const relocated = allItems.filter((i) => i.entryRelocated).length;
console.log(
  `Done. ${allItems.length} points available (${allItems.filter((i) => i.detour?.addedKm).length} with routed detours, ` +
    `${allItems.filter((i) => i.starred).length} starred, ${relocated} entry point(s) relocated).`,
);
