// Headless test for site/app.js: runs the real client script against the real
// route-data.json with a stubbed DOM and Leaflet, so boot errors are caught
// without needing a browser.
//
// The Leaflet stub deliberately enforces Leaflet's real invariant: a layer may
// not be added to a map that has no view. Violating it throws here, exactly as
// Leaflet throws inside _clipPoints ("Cannot read properties of undefined
// (reading 'min')"). An earlier version of this stub did not model that and so
// missed a genuine crash.
import fs from 'node:fs';
import vm from 'node:vm';

function el(id) {
  return {
    id, _html: '', _text: '',
    classList: { toggle(){}, add(){}, remove(){}, contains(){return false} },
    dataset: {}, style: {}, children: { length: 0 },
    set innerHTML(v){ this._html = String(v); }, get innerHTML(){ return this._html; },
    set textContent(v){ this._text = String(v); }, get textContent(){ return this._text; },
    setAttribute(){}, getAttribute(){return null}, addEventListener(){},
    value: '', hidden: false, select(){}, focus(){}, blur(){}, scrollIntoView(){},
    querySelectorAll(){ return [] }, querySelector(){ return null }, tagName: 'DIV',
    closest(){ return el('closest') }, remove(){}, appendChild(){}, click(){},
    getBoundingClientRect(){ return { height: 500, width: 900 } },
  };
}
const registry = new Map();
const document = {
  title: '',
  addEventListener(){},
  getElementById(id){ if(!registry.has(id)) registry.set(id, el(id)); return registry.get(id); },
  querySelectorAll(){ return [] },
  createElement(){ return el('created') },
  body: { appendChild(){}, removeChild(){} },
};

const violations = [];
let mapHasView = false;
const bounds = (pts) => ({
  _pts: pts,
  isValid(){ return Array.isArray(pts) && pts.length > 0 },
  pad(){ return this },
});
const layer = (pts) => ({
  addTo(m){
    if (m && m.__isMap && !mapHasView) {
      violations.push('layer added to a map with no view set');
    }
    return this;
  },
  remove(){}, clearLayers(){}, on(){}, bindPopup(){ return this },
  getBounds(){ return bounds(pts) },
});
const L = {
  map(){ return {
    __isMap: true,
    setView(){ mapHasView = true; return this },
    fitBounds(b){ if (!b) throw new TypeError("Cannot read properties of undefined (reading 'min')"); mapHasView = true; return this },
    remove(){}, on(){}, invalidateSize(){}, addLayer(){}, removeLayer(){},
  } },
  tileLayer(){ return layer([]) },
  polyline(pts){ return layer(pts) },
  layerGroup(){ return layer([]) },
  marker(pt){ return layer([pt]) },
  divIcon(){ return {} },
  latLngBounds(b){ return bounds(b) },
};

const data = JSON.parse(fs.readFileSync('site/route-data.json','utf8'));
const ctx_window = {};
const store = new Map();
const localStorage = {
  getItem: (k) => (store.has(k) ? store.get(k) : null),
  setItem: (k, v) => store.set(k, String(v)),
  removeItem: (k) => store.delete(k),
};
const ctx = {
  document, L, console,
  window: ctx_window, localStorage, Blob: class {}, URL: { createObjectURL(){return 'blob:'}, revokeObjectURL(){} },
  setTimeout, clearTimeout, Math, Date, JSON, Number, String, Array, Object, Set, Map, isNaN, Infinity,
  fetch: async () => ({ ok: true, status: 200, json: async () => data }),
};
ctx.globalThis = ctx;
ctx.window = ctx; // so `window.resolveSelection = ...` is reachable as window.resolveSelection

try {
  vm.createContext(ctx);
  // site/resolve.js is generated by the build; load it first, as app.js expects
  // window.resolveSelection to exist.
  if (!fs.existsSync('site/resolve.js')) throw new Error('site/resolve.js missing — run npm run build');
  new vm.Script(fs.readFileSync('site/resolve.js','utf8'), { filename: 'resolve.js' }).runInContext(ctx);
  new vm.Script(fs.readFileSync('site/app.js','utf8'), { filename: 'app.js' }).runInContext(ctx);
  await new Promise(r => setTimeout(r, 600));
  const sub = registry.get('route-sub');
  if (sub && /Failed to load/.test(sub.textContent)) {
    console.log('FAIL boot error:', sub.textContent); process.exit(1);
  }
  if (violations.length) {
    console.log('FAIL leaflet invariant:', [...new Set(violations)].join('; '),
                `(${violations.length} occurrences)`);
    process.exit(1);
  }
  console.log('PASS boot completed, no Leaflet invariant violations');
  console.log('  view set before layers :', mapHasView);
  console.log('  distance :', registry.get('stat-distance')?.innerHTML);
  console.log('  days     :', (registry.get('days')?.innerHTML||'').length, 'chars');
} catch (err) {
  console.log('FAIL threw:', err.constructor.name + ':', err.message);
  console.log(err.stack.split('\n').slice(0,5).join('\n'));
  process.exit(1);
}
